import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { Track } from "@/lib/mi/metrics";

export interface KommuneIntelligensSummary {
  summary: string;
  strengths: string[];
  watchouts: string[];
  generatedAt: string;
}

type State = "idle" | "loading" | "loaded" | "missing" | "error";

/**
 * Fetches the pre-generated AI summary for a (kommune, track) pair from Supabase.
 * Generated by scripts/generate-kommune-summaries.mjs (run periodically).
 * If no summary exists or the row has expired, returns state "missing".
 */
export function useKommuneIntelligensSummary(
  municipality: string | null | undefined,
  track: Track,
): { summary: KommuneIntelligensSummary | null; state: State } {
  const [summary, setSummary] = useState<KommuneIntelligensSummary | null>(null);
  const [state, setState] = useState<State>("idle");

  useEffect(() => {
    if (!municipality) {
      setSummary(null);
      setState("idle");
      return;
    }
    if (!supabase) {
      setSummary(null);
      setState("missing");
      return;
    }

    let cancelled = false;
    setState("loading");

    (async () => {
      const { data, error } = await supabase!
        .from("kommune_intelligens_summaries")
        .select("summary, strengths, watchouts, generated_at, expires_at")
        .eq("municipality", municipality)
        .eq("track", track)
        .gt("expires_at", new Date().toISOString())
        .maybeSingle();

      if (cancelled) return;
      if (error) {
        setSummary(null);
        setState("error");
        return;
      }
      if (!data) {
        setSummary(null);
        setState("missing");
        return;
      }
      setSummary({
        summary: data.summary,
        strengths: (data.strengths as string[]) ?? [],
        watchouts: (data.watchouts as string[]) ?? [],
        generatedAt: data.generated_at,
      });
      setState("loaded");
    })();

    return () => {
      cancelled = true;
    };
  }, [municipality, track]);

  return { summary, state };
}
